[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="page" type="org.springframework.data.domain.Page" --]
[#-- @ftlvariable name="node" type="co.bbs.module.node.model.Node" --]
[#-- @ftlvariable name="site" type="co.bbs.config.SiteConfig" --]
[#-- @ftlvariable name="model" type="co.bbs.core.base.BaseEntity" --]
[#-- @ftlvariable name="sec" type="co.bbs.web.tag.SpringSecurityTag" --]
[#-- @ftlvariable name="topic" type="co.bbs.module.topic.model.Topic" --]
[#-- @ftlvariable name="user" type="co.bbs.module.user.model.User" --]
[#-- @ftlvariable name="reply" type="co.bbs.moduleyy.reply.model.Reply" --]